### ISSUE TITLE
prettier config is missing

### ISSUE THREAD

**Issue by vonovak** [react-native-dialogs/react-native-dialogs#126]
@Noitidart you probably used some prettier config to format the JS files but it's not in the repo, do you think you can add it?

Also, I'm planning to upgrade the lib to the latest version of the underlying native library, which will probably result in some non-exactly-small changes. You okay with that? Thanks.

**Comment by Noitidart** [comment]
Hey @vonovak I actually didn't use prettier, but I support going that way. We should also probably remove flow support and switch to TypeScript.

Thanks for asking. An upgrade would be awesome, but hopefully all existing features remain.

**Comment by vonovak** [comment]
hi, thanks for comment. Removing Flow is currently not what I'm after - I just want to upgrade the underlying native lib and make any necessary changes to the api. 

> but hopefully all existing features remain 

actually, there will be some removals. eg. progress dialog is removed and some more options are removed.
